# SPDX-License-Identifier: Apache-2.0
"""Render the token-level attention dumps of video DiTs.

Where ``plot_chunk_attention_maps`` answers "how much mass does this chunk send
to that chunk?", this answers the finer question "*which individual latent
tokens* does it land on?" — the probe keeps the key axis unreduced, so every
key token has a score and the token axis folds straight back into the latent
grid of each frame.

Reads a run directory produced by the attention-map probe with
``SGLANG_DIFFUSION_ATTENTION_MAP_TOKEN_SCORES=true`` (see
``runtime/utils/attention_map_probe.py``) and writes, per generating chunk, the
received-attention map of every latent frame, plus a per-layer summary.

Scores are shown as a multiple of uniform attention: each row is a distribution
over the tokens that were visible to that chunk, so 1.0 means "exactly the mass
a flat attention would give this token" and 10 means "10x more".

Example:

    SGLANG_DIFFUSION_ATTENTION_MAP_DIR=/data/attn \\
    SGLANG_DIFFUSION_ATTENTION_MAP_TOKEN_SCORES=true sglang generate \\
        --model-path /data/models/LongVie2-Diffusers --prompt "..." ...

    python -m sglang.multimodal_gen.tools.plot_token_attention_maps \\
        /data/attn/LongVie2Transformer3DModel-20260722-101500
"""

import argparse
import json
import pathlib
import warnings

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LogNorm, Normalize
from matplotlib.patches import Rectangle

HEATMAP_CMAP = "magma"
MASKED_COLOR = "#e8e8e8"


class TokenRun:
    """A loaded ``token_scores.npz`` folded onto the latent grid."""

    def __init__(
        self, run_dir: pathlib.Path, grid: tuple[int, int] | None = None
    ) -> None:
        meta_path = run_dir / "meta.json"
        self.meta = json.loads(meta_path.read_text()) if meta_path.exists() else {}
        scores_path = run_dir / "token_scores.npz"
        if not scores_path.exists():
            raise SystemExit(
                f"{run_dir} has no token_scores.npz — re-run the probe with "
                "SGLANG_DIFFUSION_ATTENTION_MAP_TOKEN_SCORES=true"
            )
        with np.load(scores_path) as data:
            scores = data["token_scores"]  # [chunks, layers, heads, tokens]

        # dumps written before the probe recorded the latent grid only carry the
        # tokens-per-frame product, which does not determine the split
        if grid is None and "grid_height" not in self.meta:
            raise SystemExit(
                f"{run_dir}/meta.json predates the recorded latent grid; pass "
                "--grid HxW (e.g. --grid 30x52 for 832x480 Wan)"
            )
        self.grid_height, self.grid_width = grid or (
            int(self.meta["grid_height"]),
            int(self.meta["grid_width"]),
        )
        frame_seqlen = self.grid_height * self.grid_width
        chunks, layers, heads, tokens = scores.shape
        assert tokens % frame_seqlen == 0, (
            f"{tokens} tokens is not a whole number of "
            f"{self.grid_height}x{self.grid_width} frames"
        )
        self.num_chunks = chunks
        self.num_layers = layers
        self.num_heads = heads
        self.num_latent_frames = tokens // frame_seqlen
        # [chunks, layers, heads, frames, height, width]
        self.scores = scores.reshape(
            chunks, layers, heads, self.num_latent_frames, self.grid_height,
            self.grid_width,
        )
        # every row is a distribution over the tokens that were visible to that
        # chunk, so scaling by their count puts "uniform attention" at 1.0
        visible = np.isfinite(scores[:, 0, 0, :]).sum(axis=1)
        self.uniform_scale = visible.astype(np.float32)[
            :, None, None, None, None, None
        ]

    def frames_of_chunk(self, chunk_index: int) -> tuple[int, int]:
        """Latent frame range generated by ``chunk_index``, as a half-open pair.

        Empty for a full-attention model, where the single "chunk" is the whole
        video and marking every frame as its own would say nothing.
        """
        block = int(self.meta.get("num_frames_per_block", self.num_latent_frames))
        if block >= self.num_latent_frames:
            return 0, 0
        return chunk_index * block, min(
            (chunk_index + 1) * block, self.num_latent_frames
        )

    def chunk_map(self, chunk_index: int) -> np.ndarray:
        """Head- and layer-averaged ``[frames, height, width]``, in uniform units."""
        return _nanmean(
            self.scores[chunk_index] * self.uniform_scale[chunk_index], axis=(0, 1)
        )

    def layer_frame_maps(self, chunk_index: int) -> np.ndarray:
        """Head-averaged ``[layers, frames, height, width]``, in uniform units."""
        return _nanmean(
            self.scores[chunk_index] * self.uniform_scale[chunk_index], axis=1
        )

    def per_layer_spatial(self) -> np.ndarray:
        """``[layers, height, width]``: where in a frame each layer looks.

        Averaged over heads, frames and generating chunks, so this is the
        absolute-position preference of a layer rather than a temporal profile.
        """
        return _nanmean(self.scores * self.uniform_scale, axis=(0, 2, 3))


def _nanmean(values: np.ndarray, axis) -> np.ndarray:
    """``np.nanmean`` without the all-NaN-slice warning (never-visible tokens)."""
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)
        return np.nanmean(values, axis=axis)


def _norm(values: np.ndarray, color_scale: str):
    finite = values[np.isfinite(values) & (values > 0)]
    vmax = float(finite.max()) if finite.size else 1.0
    if color_scale == "log":
        vmin = max(float(finite.min()) if finite.size else 1e-3, vmax * 1e-3)
        return LogNorm(vmin=vmin, vmax=vmax)
    return Normalize(vmin=0.0, vmax=vmax)


def _for_display(values: np.ndarray, norm) -> np.ndarray:
    """Lift exact zeros onto the log floor so they read as "no attention"."""
    if not isinstance(norm, LogNorm):
        return values
    return np.where(np.isnan(values) | (values > norm.vmin), values, norm.vmin)


def _draw(axes, image: np.ndarray, norm, cmap) -> None:
    axes.imshow(
        np.ma.masked_invalid(_for_display(image, norm)),
        origin="upper",
        interpolation="nearest",
        cmap=cmap,
        norm=norm,
    )
    axes.set_xticks([])
    axes.set_yticks([])


def _subsample(count: int, limit: int) -> np.ndarray:
    """At most ``limit`` evenly spaced indices out of ``count``, ends included."""
    if count <= limit:
        return np.arange(count)
    return np.unique(np.linspace(0, count - 1, limit).round().astype(int))


def _colorbar(figure, norm, cmap, *, axes, color_scale: str) -> None:
    mappable = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
    colorbar = figure.colorbar(mappable, ax=axes, pad=0.01, fraction=0.03)
    colorbar.set_label(
        "attention mass / uniform" + (" (log)" if color_scale == "log" else ""),
        fontsize=9,
    )


def plot_chunk_frames(
    run: TokenRun,
    chunk_index: int,
    *,
    out_path: pathlib.Path,
    color_scale: str,
    dpi: int,
) -> None:
    """One panel per latent frame: which tokens this chunk's queries land on."""
    maps = run.chunk_map(chunk_index)  # [frames, height, width]
    own_start, own_end = run.frames_of_chunk(chunk_index)
    columns = min(run.num_latent_frames, 7)
    rows = int(np.ceil(run.num_latent_frames / columns))
    cell = 1.7 * run.grid_width / max(run.grid_height, 1)
    figure, axes = plt.subplots(
        rows,
        columns,
        figsize=(cell * columns + 1.4, 1.7 * rows + 1.1),
        squeeze=False,
        constrained_layout=True,
    )
    cmap = plt.get_cmap(HEATMAP_CMAP).with_extremes(bad=MASKED_COLOR)
    norm = _norm(maps, color_scale)

    for index, axis in enumerate(axes.flat):
        if index >= run.num_latent_frames:
            axis.axis("off")
            continue
        _draw(axis, maps[index], norm, cmap)
        is_own = own_start <= index < own_end
        axis.set_title(
            f"frame {index}" + (" (self)" if is_own else ""),
            fontsize=8,
            fontweight="bold" if is_own else "normal",
        )
        if is_own:
            axis.add_patch(
                Rectangle(
                    (-0.5, -0.5),
                    run.grid_width,
                    run.grid_height,
                    fill=False,
                    edgecolor="white",
                    linewidth=1.6,
                    linestyle="--",
                )
            )
    figure.suptitle(
        f"Chunk {chunk_index} — attention received per latent token\n"
        f"{run.meta.get('model_tag', '')} · mean over "
        f"{run.num_layers} layers, {run.num_heads} heads, denoising steps",
        fontsize=10,
    )
    _colorbar(figure, norm, cmap, axes=axes, color_scale=color_scale)
    figure.savefig(out_path, dpi=dpi)
    plt.close(figure)


def plot_chunk_layers(
    run: TokenRun,
    chunk_index: int,
    *,
    out_path: pathlib.Path,
    color_scale: str,
    dpi: int,
    max_layers: int,
    max_frames: int,
) -> None:
    """Layer x frame small multiples, to see depth change the spatial pattern."""
    maps = run.layer_frame_maps(chunk_index)  # [layers, frames, height, width]
    layers = _subsample(run.num_layers, max_layers)
    frames = _subsample(run.num_latent_frames, max_frames)
    own_start, own_end = run.frames_of_chunk(chunk_index)

    cell = 1.35 * run.grid_width / max(run.grid_height, 1)
    figure, axes = plt.subplots(
        len(layers),
        len(frames),
        figsize=(cell * len(frames) + 2.0, 1.35 * len(layers) + 1.2),
        squeeze=False,
        constrained_layout=True,
    )
    cmap = plt.get_cmap(HEATMAP_CMAP).with_extremes(bad=MASKED_COLOR)
    norm = _norm(maps[np.ix_(layers, frames)], color_scale)

    for row, layer in enumerate(layers):
        for column, frame in enumerate(frames):
            axis = axes[row][column]
            _draw(axis, maps[layer, frame], norm, cmap)
            if row == 0:
                axis.set_title(
                    f"frame {frame}" + ("\n(self)" if own_start <= frame < own_end else ""),
                    fontsize=8,
                )
            if column == 0:
                axis.set_ylabel(f"layer {layer}", fontsize=8)
    figure.suptitle(
        f"Chunk {chunk_index} — token attention by layer · "
        f"{run.meta.get('model_tag', '')} (head mean)",
        fontsize=10,
    )
    _colorbar(figure, norm, cmap, axes=axes, color_scale=color_scale)
    figure.savefig(out_path, dpi=dpi)
    plt.close(figure)


def plot_layer_summary(
    run: TokenRun, *, out_path: pathlib.Path, color_scale: str, dpi: int
) -> None:
    """Every layer's frame-averaged spatial preference, in absolute coordinates."""
    maps = run.per_layer_spatial()  # [layers, height, width]
    columns = min(run.num_layers, 8)
    rows = int(np.ceil(run.num_layers / columns))
    cell = 1.5 * run.grid_width / max(run.grid_height, 1)
    figure, axes = plt.subplots(
        rows,
        columns,
        figsize=(cell * columns + 1.6, 1.5 * rows + 1.0),
        squeeze=False,
        constrained_layout=True,
    )
    cmap = plt.get_cmap(HEATMAP_CMAP).with_extremes(bad=MASKED_COLOR)
    norm = _norm(maps, color_scale)
    for index, axis in enumerate(axes.flat):
        if index >= run.num_layers:
            axis.axis("off")
            continue
        _draw(axis, maps[index], norm, cmap)
        axis.set_title(f"layer {index}", fontsize=8)
    figure.suptitle(
        f"Spatial attention preference per layer · {run.meta.get('model_tag', '')}\n"
        "mean over heads, latent frames and generating chunks",
        fontsize=10,
    )
    _colorbar(figure, norm, cmap, axes=axes, color_scale=color_scale)
    figure.savefig(out_path, dpi=dpi)
    plt.close(figure)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("run_dir", type=pathlib.Path, help="probe output directory")
    parser.add_argument(
        "--out-dir",
        type=pathlib.Path,
        default=None,
        help="where to write the figures (default: <run_dir>/token_plots)",
    )
    parser.add_argument("--color-scale", choices=("log", "linear"), default="log")
    parser.add_argument("--max-layers", type=int, default=8)
    parser.add_argument("--max-frames", type=int, default=8)
    parser.add_argument("--dpi", type=int, default=140)
    parser.add_argument(
        "--grid",
        default=None,
        help="latent grid as HxW; only needed for dumps written before the "
        "probe recorded it (e.g. 30x52 for 832x480 Wan)",
    )
    args = parser.parse_args()

    grid = None
    if args.grid is not None:
        height, width = args.grid.lower().split("x")
        grid = (int(height), int(width))
    run = TokenRun(args.run_dir, grid)
    out_dir = args.out_dir or args.run_dir / "token_plots"
    out_dir.mkdir(parents=True, exist_ok=True)

    for chunk_index in range(run.num_chunks):
        plot_chunk_frames(
            run,
            chunk_index,
            out_path=out_dir / f"chunk_{chunk_index:03d}_frames.png",
            color_scale=args.color_scale,
            dpi=args.dpi,
        )
        plot_chunk_layers(
            run,
            chunk_index,
            out_path=out_dir / f"chunk_{chunk_index:03d}_layers.png",
            color_scale=args.color_scale,
            dpi=args.dpi,
            max_layers=args.max_layers,
            max_frames=args.max_frames,
        )
    plot_layer_summary(
        run,
        out_path=out_dir / "layer_summary.png",
        color_scale=args.color_scale,
        dpi=args.dpi,
    )
    print(f"wrote {2 * run.num_chunks} chunk figures + layer_summary.png to {out_dir}")


if __name__ == "__main__":
    main()
